# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 主页
    url: /
    weight: 10
  - name: 文档
    url: docs/
    weight: 20
  - name: 日志
    url: blog/
    weight: 30
  # - name: 展示
  #   url: showcase/
  #   weight: 40
  # - name: 交流
  #   url: community/
  #   weight: 50

sidebar:
  - identifier:
    name: 其它
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "联系作者"
    pageRef: "/community"
    weight: 2
  # - identifier: hugoDocs
  #   name: "Hugo Docs ↗"
  #   url: "https://docs.hugoblox.com"
  #   weight: 3
